### ISSUE TITLE
brittle modification of Armadillo internals

### ISSUE THREAD

**Issue by conradsnicta** [armstrtw/CppBugs#19]
@armstrtw @eddelbuettel - CppBugs does brittle modifications of Armadillo internals, for example:
https://github.com/armstrtw/CppBugs/blob/master/cppbugs/mcmc.arma.extensions.hpp#L28

Modifications like the above are not guaranteed to work, as Armadillo internals are explicitly marked as being subject to change between versions.  In fact, the above modifications won't work with Armadillo 7.900.

The public API in Armadillo is guaranteed to be stable, but not the internals:
http://arma.sourceforge.net/docs.html#api_additions

I recommend the affected code in CppBugs be refactored to not use this brittle approach.

**Comment by eddelbuettel** [comment]
CppBugs is not an active package on CRAN, see [its page stating the July 2016 withdrawal](https://cran.r-project.org/web/packages/rcppbugs/index.html).

The problem we have with RcppArmadillo is package dfcomb and dfmta _embedding_ and _even older copy_ but that is not something we can blame CppBugs for.

I recommend this be closed.

**Comment by armstrtw** [comment]
@conradsnicta it's not really active anymore.  stan has been such a dominating force, I just recommend people to use it when I get the occasional cppbugs request.  I did move the likelihood bits of the project to another repo, here https://github.com/armaMCMC/arma-log-likelihood, but I can't claim that's an active project either.

**Comment by conradsnicta** [comment]
ok, I see.
